#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28
#What is the value of the first triangle number to have over five hundred divisors?

def divisors_count(n):
    if n ** 0.5 % 1 == 0:
        count = 1
    else:
        count = 0
    for i in range(1, int(n ** 0.5)):
        if n % i == 0:
            count +=2
    return count


def higly_triangular_number(end):
    higher_count = 0
    acc = 0
    i = 1
    while higher_count <= end:
        acc += i
        if divisors_count(acc) > higher_count:
            higher_count = divisors_count(acc)
        i += 1
    return acc

print(higly_triangular_number(500))
